import { CalendarDays, MapPin, BookOpen, Heart, FileText, HandHeart, Moon, Camera } from 'lucide-react';
import Registration from './registration';
import {Navigation,PageInteractions} from './interactions';
export default function Home() {
 const experiences=[{icon:HandHeart,title:'Prayer',text:'Let us pray with you and for you.',tone:'blue',photo:'prayer',alt:'Hands clasped in prayer'},{icon:BookOpen,title:'Free Bibles',text:'Take a Bible. Read the truth. Discover hope.',tone:'green',photo:'bible',alt:'An open Bible'},{icon:FileText,title:'Gospel Tracts',text:'Take one. Share hope. Plant a seed.',tone:'gold',photo:'tracts',alt:'Gospel tracts sharing a message of hope'},{icon:Heart,title:'Encouragement',text:'Real people. Real conversations. A real hope.',tone:'red',photo:'hope',alt:'Sunrise over a forested mountain landscape'}];
 return <><Navigation/><PageInteractions/><main id="home"><section className="hero" aria-label="Tent of Hope event"><h1 className="sr-only">Tent of Hope — Jesus is our Hope</h1><img src="/hope-banner.png" alt="Tent of Hope: a journey from fear to hope. Jesus is our hope. Bonnieville, Kentucky. Sharing the hope we have in Jesus. Romans 10:13." fetchPriority="high"/></section><div className="event-strip"><div><span><MapPin size={18}/> Hill of Terror · Bonnieville, Kentucky</span><span><CalendarDays size={18}/> Sept. 18–Oct. 31, 2026</span><span><Moon size={18}/> Fridays &amp; Saturdays · Dusk–Midnight (CDT)</span></div></div>
 <section id="about" className="about-section section-shell"><div className="about-heading" data-reveal><p className="eyebrow">UNITED SERVANTS FOR JESUS PRESENTS</p><h2>Tent of Hope<em>.</em></h2><p className="intro">A Community United by Hope.</p><p className="opening-date">Opening date — Friday, Sept. 18</p></div><div className="about-copy" data-reveal><p>Tent of Hope is a ministry outreach event at Hill of Terror in Bonnieville, Kentucky, sharing the hope we have in Jesus through prayer, Bible distribution, gospel tracts, and encouragement.</p><p>Our desire is to meet people where they are, bless our community, and point hearts to the life-changing hope found in Christ.</p></div></section>
 <section id="expect" className="expect-section"><div className="section-shell"><div className="section-heading" data-reveal><div><p className="eyebrow">REAL PEOPLE. REAL CONVERSATIONS.</p><h2>Hope, shared in simple ways.</h2></div><p>Prayer, the Word, and encouragement.<br/>Experience a community that cares.</p></div><div className="experience-grid">{experiences.map(({icon:Icon,title,text,tone,photo,alt},index)=><article className="experience" key={title} data-reveal data-delay={index*70}><div className={"experience-photo photo-"+photo} role="img" aria-label={alt}/><div className="experience-copy"><span className={'icon-wrap '+tone}><Icon size={25} strokeWidth={1.6}/></span><h3>{title}</h3><p>{text}</p></div></article>)}</div></div></section>
 <section className="scripture-section section-shell" data-reveal><span className="quote-mark" aria-hidden="true">“</span><div className="scripture-quotes"><blockquote><p>For everyone who calls on the name of the Lord will be saved.</p><cite>ROMANS 10:13</cite></blockquote><blockquote><p>“I am the light of the world. Whoever follows me will never walk in darkness, but will have the light of life.”</p><cite>— JOHN 8:12</cite></blockquote></div></section>
 <section id="register" className="registration-section"><div className="registration-layout section-shell"><div className="registration-intro" data-reveal><p className="eyebrow">TAKE YOUR NEXT STEP</p><h2>There’s a place<br/>for <em>you.</em></h2><p>Join us for Tent of Hope. Come to receive encouragement, connect with others, or serve as a volunteer.</p><div className="registration-detail"><MapPin size={22}/><div><strong>Hill of Terror</strong><span>Bonnieville, Kentucky</span></div></div><div className="registration-detail"><CalendarDays size={22}/><div><strong>Sept. 18–Oct. 31, 2026</strong><span>Fridays &amp; Saturdays</span><span>Dusk–Midnight (CDT)</span></div></div><p className="registration-note">Register your interest today. Please check this page for event updates.</p></div><Registration/></div></section><section className="closing"><p>People · Prayer · Bibles · Hope · Jesus</p><h2>Same hope. A brighter tomorrow.</h2></section></main><footer className="usfj-footer"><div className="footer-brand"><a href="#home" aria-label="United Servants For Jesus home"><img src="/usfj-dark.png" alt="USFJ — United Servants For Jesus"/></a></div><div className="footer-navy"><div className="footer-columns"><section><h2>Useful Links</h2><ul><li><a href="#about">About Us</a></li><li><a href="#register">Join USFJ</a></li><li><a href="#register">Volunteer</a></li><li><a href="/events">Events</a></li></ul></section><section><h2>Our Causes</h2><ul><li>Administrative Support</li><li>Housing Facility</li><li>Support</li></ul></section><section><h2>Social Media</h2><ul className="social-list"><li><span className="facebook-icon" aria-hidden="true">f</span>Facebook</li><li><Camera size={19} aria-hidden="true"/>Instagram</li><li><span className="x-icon" aria-hidden="true">𝕏</span>X</li></ul></section><section id="contact"><h2>Contact Information</h2><address>1100 Ring Road,<br/>Elizabethtown,<br/>KY 42701.<br/><a href="tel:+15024882005">+1(502) 488 2005</a><br/><a href="mailto:info@usfjesus.org">info@usfjesus.org</a></address></section></div><div className="footer-credit"><span>© {new Date().getFullYear()} All rights reserved.</span><span className="credit-divider" aria-hidden="true"/><span>Designed by <a href="https://kaltechconsultancy.tech" target="_blank" rel="noopener noreferrer">Kaltech Consultancy</a></span></div></div></footer></>;
}
