'use client';
import {useState,useRef} from 'react';
import {CheckCircle2,ShieldCheck,LoaderCircle,UserRound,Mail} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
export default function Registration(){
 const [type,setType]=useState('Attendee'),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(false);const key=useRef('');
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');if(!consent){setError('Please agree to the event registration notice.');return;}setBusy(true);const data=Object.fromEntries(new FormData(e.currentTarget));if(!key.current)key.current=crypto.randomUUID();try{const r=await fetch('/api/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,type,consent,key:key.current})});const result=await r.json() as {error?:string};if(!r.ok)throw new Error(result.error||'We couldn’t save your registration. Please try again.');setSuccess(true);}catch(err){setError(err instanceof Error?err.message:'Something went wrong. Please try again.');}finally{setBusy(false);}}
 return <div className="registration-card"><div className="card-heading"><p className="eyebrow">YOU’RE INVITED</p><h2>Join us at Tent of Hope</h2><p>We’d love to welcome you.</p></div>{success?<div className="success" role="status"><CheckCircle2 size={50}/><h3>You’re on the list!</h3><p>Thank you for registering for Tent of Hope. Your registration has been saved.</p><p>Tent of Hope takes place Fridays and Saturdays, Sept. 18–Oct. 31, 2026, from dusk to midnight CDT. The venue is Hill of Terror in Bonnieville, Kentucky. Please check this page for updates.</p><span className="success-signoff">We look forward to welcoming you.</span></div>:<form onSubmit={submit}><p className="form-note">Register your interest below. <span>* Required</span></p><div className="fields"><label className="full">Full name <b>*</b><span className="form-icon-field"><UserRound size={19} aria-hidden="true"/><input name="name" autoComplete="name" placeholder="Your full name" required minLength={2} maxLength={120}/></span></label><label className="full">Email address <b>*</b><span className="form-icon-field"><Mail size={19} aria-hidden="true"/><input name="email" type="email" autoComplete="email" placeholder="you@example.com" required maxLength={254}/></span></label><label>Phone <span>(optional)</span><input name="phone" type="tel" autoComplete="tel" placeholder="Your phone number" maxLength={40}/></label><label>City, state <b>*</b><input name="city" autoComplete="address-level2" placeholder="Bonnieville, KY" required minLength={2} maxLength={120}/></label><label>Number attending <b>*</b><input name="attendees" type="number" min="1" max="50" defaultValue="1" required/></label><div className="field"><label htmlFor="type">I’m joining as <b>*</b></label><Select value={type} onValueChange={setType}><SelectTrigger id="type" className="type-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="Attendee">Attendee</SelectItem><SelectItem value="Volunteer">Volunteer</SelectItem></SelectContent></Select></div><label className="full">Prayer request <span>(optional)</span><textarea name="prayer" placeholder="How can we pray for you?" maxLength={2000} rows={3}/><small>Share only what you’re comfortable sharing with the USFJ team.</small></label></div><div className="consent"><Checkbox id="consent" checked={consent} onCheckedChange={v=>setConsent(v===true)}/><label htmlFor="consent">I agree that USFJ may use these details to manage my registration and contact me about Tent of Hope. Any prayer request I share may be read by the ministry team. <b>*</b></label></div>{error&&<p role="alert" className="error">{error}</p>}<button className="register-button" disabled={busy} type="submit">{busy?<><LoaderCircle className="spin" size={19}/> Saving registration…</>:<>Register now</>}</button><p className="privacy-note"><ShieldCheck size={16}/> Your information is not displayed publicly.</p></form>}</div>;
}
